"""Deterministic LibPinMAME harness scenarios for the four Spooky Pinball pinHeck games.

Every pinHeck ROM has the same operator menu: Enter (public 6) opens it, the right flipper button
(public 112, copied by core_updateSw into cabinet switch 3) steps to the next item, Enter starts the
selected test and Back (public 5) leaves it. Only the menu order differs per firmware, so each game
declares how many right-flipper steps reach each test. The scenarios walk:

- switch: the Switch Edge test, closing every host-writable public switch in turn and snapshotting
  the frame while it is held (the ROM draws matrix closures in its 8x8 grid and names cabinet inputs);
- solenoid: the Solenoid test, snapshotting each item's name and pressing Enter to fire it;
- lamp: the Lamp test, snapshotting every item;
- servo: the Servo test (not in The Jetsons V4), snapshotting each item and pressing Enter to set it;
- rgb: the RGB Lighting test, snapshotting each item and pressing Enter;
- game: no menu at all. The trough switches start closed, Start (94) is pressed in attract mode and the
  ball serve and the first seconds of play are observed once per second.

Run ``--write`` to (re)generate tools/harness-scenarios/pinheck/*.json and ``--check`` to refuse drift.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / "tools" / "harness-scenarios" / "pinheck"
ENTER, BACK, NEXT = 6, 5, 112

# Right-flipper steps from the item the menu opens on to each test (firmware menus observed on 2026-10-05).
MENUS = {
	"amh": {"switch": 3, "solenoid": 5, "servo": 6, "lamp": 8, "rgb": 9},
	"dominos": {"switch": 0, "solenoid": 2, "servo": 3, "lamp": 4, "rgb": 5},
	"rzspook": {"switch": 0, "solenoid": 2, "servo": 3, "lamp": 4, "rgb": 5},
	"jetsons": {"switch": 0, "solenoid": 2, "lamp": 3, "rgb": 4},
}
# Trough contacts closed before a game starts (factory charts; The Jetsons' first trough position is cabinet opto 92).
TROUGHS = {"amh": [84, 85, 86, 87], "dominos": [12, 13, 14], "rzspook": [12, 13, 14, 15, 16, 17, 18], "jetsons": [52, 53, 54, 92]}
START = 94
# Items to walk; a walk that passes the end wraps back to the first item, which the snapshots show.
ITEMS = {"solenoid": 28, "lamp": 96, "servo": 12, "rgb": 12}
# America's Most Haunted's RGB test has a GHOST TYPE item (item 10) whose Enter switches the ghost LED from REV 1 to
# REV 2; the longer walk shows every ghost colour again under REV 2.
GAME_ITEMS = {("amh", "rgb"): 16}
# Host-writable switches: 1 (coin door) is toggled separately, 3/4 are overwritten from 112/114 every vblank,
# 5/6 would leave or restart the test.
SWITCHES = [2, 7, 8, *[d * 10 + r for d in range(1, 10) for r in range(1, 9)], 112, 114]
STATE_NOTE = {
	"amh": "Fresh empty state directory: America's Most Haunted programs its PIC32 from the Intel HEX at start and needs no flashing.",
}
FLASHED_NOTE = ("State directory seeded from the game's own post-update NVRAM: on an empty state the ROM programs its program "
                "flash and AV EEPROM from the romset (about eight emulated minutes) and asks for a restart, twice; the "
                "seeded NVRAM is that result, retained and hashed with the run.")


def pulse(switch: int, label: str, *, hold_ms: int = 250, settle_s: float = 1.5, held: bool = False) -> dict:
	action = {"type": "pulse", "switch": switch, "hold_ms": hold_ms, "settle_s": settle_s, "label": label}
	if held:
		action["snapshot_while_held"] = True
	return action


def game_scenario(game: str) -> dict:
	actions = [{"type": "wait", "seconds": 5, "label": "Attract mode with a full trough"},
	           pulse(START, "Press Start", hold_ms=300, settle_s=1.0)]
	actions += [{"type": "wait", "seconds": 1.0, "label": f"Game second {second:02d}"} for second in range(1, 21)]
	notes = (f"{STATE_NOTE.get(game, FLASHED_NOTE)} The trough contacts {TROUGHS[game]} are closed from power-up, Start (94) "
	         "is pressed in attract mode and the ball serve is observed once per second; nothing else is touched. Generated by "
	         "tools/pinheck_harness_scenarios.py.")
	return {"format": "pinmame-harness-scenario", "version": 1, "game": game, "notes": notes,
	        "initial_switches": [{"switch": switch, "state": 1} for switch in TROUGHS[game]],
	        "watch_switches": [1, 94, *TROUGHS[game]], "actions": actions}


# America's Most Haunted's top lanes: which of the O, R and B lamps (public 51-53) each lane switch lights in a game.
LANE_SWITCHES = [61, 62, 63]


def lanes_scenario(game: str) -> dict:
	result = game_scenario(game)
	result["actions"] = result["actions"][:2] + [
		{"type": "wait", "seconds": 2.0, "label": "Game running"},
		{"type": "set_switch", "switch": 84, "state": 0, "settle_s": 0.5, "label": "Ball leaves trough position 1 (84 open)"},
		{"type": "set_switch", "switch": 82, "state": 1, "settle_s": 2.0, "label": "Ball on the shooter lane (82 closed)"},
		{"type": "set_switch", "switch": 82, "state": 0, "settle_s": 2.0, "label": "Ball plunged (82 open)"}]
	result["actions"] += [pulse(switch, f"Close {switch}", hold_ms=300, settle_s=1.5) for switch in LANE_SWITCHES]
	result["notes"] = result["notes"].replace(
		"is pressed in attract mode and the ball serve is observed once per second; nothing else is touched",
		"is pressed in attract mode, the serve is simulated (84 opens, 82 closes, then opens as the ball is plunged), then "
		f"the top-lane switches {LANE_SWITCHES} are closed one at a time to see which of the O, R and B lamps (public 51-53) "
		"each one lights")
	return result


def scenario(game: str, test: str) -> dict:
	if test == "game":
		return game_scenario(game)
	if test == "lanes":
		return lanes_scenario(game)
	actions = [{"type": "wait", "seconds": 3, "label": "Attract mode"}, pulse(ENTER, "Open the operator menu", settle_s=2.5)]
	actions += [pulse(NEXT, f"Menu step {index + 1}") for index in range(MENUS[game][test])]
	actions.append(pulse(ENTER, f"Start the {test} test", settle_s=2.5))
	if test == "switch":
		actions += [pulse(switch, f"Close {switch}", hold_ms=1300, settle_s=0.5, held=True) for switch in SWITCHES]
		actions += [{"type": "set_switch", "switch": 1, "state": 0, "settle_s": 1.0, "label": "Open the coin door (1 released)"},
		            {"type": "set_switch", "switch": 1, "state": 1, "settle_s": 1.0, "label": "Close the coin door (1 held)"}]
	else:
		for index in range(1, GAME_ITEMS.get((game, test), ITEMS[test]) + 1):
			actions.append({"type": "wait", "seconds": 0.4, "label": f"Item {index:02d}"})
			if test != "lamp":
				actions.append(pulse(ENTER, f"Enter on item {index:02d}", settle_s=1.5))
			actions.append(pulse(NEXT, f"Next after item {index:02d}", settle_s=1.2))
	actions.append(pulse(BACK, "Leave the test", settle_s=2.0))
	notes = (f"{STATE_NOTE.get(game, FLASHED_NOTE)} Operator menu: Enter (6) opens it, the right flipper button (112) steps, "
	         f"Enter starts the {test} test, Back (5) leaves. Generated by tools/pinheck_harness_scenarios.py.")
	return {"format": "pinmame-harness-scenario", "version": 1, "game": game, "notes": notes,
	        "watch_switches": [1, 3, 4, 94], "actions": actions}


def artifacts() -> dict[Path, bytes]:
	return {DIRECTORY / f"{game}-{test}.json": (json.dumps(scenario(game, test), indent=2) + "\n").encode()
	        for game, tests in MENUS.items() for test in (*tests, "game", *(("lanes",) if game == "amh" else ()))}


def main() -> None:
	parser = argparse.ArgumentParser(description=__doc__)
	mode = parser.add_mutually_exclusive_group(required=True)
	mode.add_argument("--write", action="store_true")
	mode.add_argument("--check", action="store_true")
	args = parser.parse_args()
	for path, payload in artifacts().items():
		if args.check:
			if not path.is_file() or path.read_bytes() != payload:
				raise SystemExit(f"Scenario drift: {path.relative_to(ROOT).as_posix()}")
		else:
			path.parent.mkdir(parents=True, exist_ok=True)
			path.write_bytes(payload)
	print(f"{len(artifacts())} pinHeck scenarios {'match' if args.check else 'written'}")


if __name__ == "__main__":
	main()
